FORMAT: 1A
HOST: http://api.spiderlog.net

# Spider Log API
Provides services for the Spider Log app family, recording the worlds spider sightings

# Group Spiders
Access to Spider Resources

## My Spiders [/spiders]
### Get all my spider sightings [GET]
+ Request

        +Header
    
                Authorization: Basic dXNlcjpwYXNzd29yZA==
        
+ Response 200 (application/json)
        
        [
            {
                "sightedAt" : "2014-08-29T19:00",
                "imageUrl" : "uid:34225/4699046e5d_z.jpg",
                "description" : "Spider I saw at home",
                "tags": [
                    "big",
                    "stripy"
                    ]
            },
            {
                "sightedAt" : "2014-08-29T19:00",
                "imageUrl" : "uid:34225/4699046e5d_z.jpg",
                "description" : "Spider I saw at home",
                "tags": [
                        "big",
                        "stripy"
                        ]
            }
            
        ]