FORMAT: 1A
HOST: http://api.spiderlog.net

# Spider Log API
Provides services for the Spider Log app family, recording the worlds spider sightings

# Group Spiders
Access to Spider Resources

## My Spiders [/spiders]
### Get all my spider sightings [GET]
+ Request

    +Header
    
        Authorization